const SHOP_DATA = [
  //avatar-under-pants.glb
  {
    id: 1,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode:
      "https://api.echo3d.com/webar?key=plain-dream-0556&entry=e4efaa72-3e83-429c-be0e-77160649d30b",
    url: "/models/Coelte.glb",
    price: 250,
  },
  {
    id: 2,
    name: "Wiz Carmagnole Jacket",
    position: [0, -110, -25],
    stock: 12,
    qrCode:
      "https://api.echo3d.com/webar?key=plain-dream-0556&entry=ea75a3a8-f821-4971-9497-3d40d23ea87f",
    url: "/models/Casaco.glb",
    price: 670,
  },
  {
    id: 3,
    name: "Wiz Mint Jacket",
    position: [0, -110, -20],
    stock: 12,
    qrCode:
      "https://api.echo3d.com/webar?key=plain-dream-0556&entry=6783f8d7-e082-4dcb-93ee-23077d400422",
    url: "/models/Colt.glb",
    price: 650,
  },
  {
    id: 4,
    name: "TechBrief Cargo",
    position: [0, -70, 0],
    stock: 12,
    qrCode:
      "https://api.echo3d.com/webar?key=plain-dream-0556&entry=6783f8d7-e082-4dcb-93ee-23077d400422",
    url: "/models/Pants.glb",
    price: 250,
  },
  {
    id: 5,
    name: "Future cape",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.com/eomx",
    url: "/models/T-shirt black.glb",
    price: 250,
  },
  {
    id: 6,
    name: "Cargo shirt",
    position: [0, -120, 0],
    stock: 12,
    qrCode:
      "https://api.echo3d.com/webar?key=plain-dream-0556&entry=d05d803a-b7c2-44a3-9326-acff870c2f12",
    url: "/models/T-shirt green.glb",
    price: 250,
  },

  {
    id: 7,
    name: "Skin-tight Tee",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    url: "/models/Underwear.glb",
    price: 250,
  },
  // {
  //   id: 8,
  //   name: "Avatar 1",
  //   position: [0, -120, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-under-pants.glb",
  //   price: 250,
  // },
  // {
  //   id: 9,
  //   name: "Avatar 2",
  //   position: [0, -110, -25],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-pants.glb",
  //   price: 670,
  // },
  // {
  //   id: 10,
  //   name: "Avatar 3",
  //   position: [0, -110, -20],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-cape.glb",
  //   price: 650,
  // },
  // {
  //   id: 11,
  //   name: "Avatar 4",
  //   position: [0, -70, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-pants-and-vest.glb",
  //   price: 250,
  // },
  // {
  //   id: 12,
  //   name: "Avatar 5",
  //   position: [0, -120, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-tee-shirt-1.glb",
  //   price: 250,
  // },
  // {
  //   id: 13,
  //   name: "Avatar 6",
  //   position: [0, -120, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-tee-shirt-2.glb",
  //   price: 250,
  // },
  // {
  //   id: 14,
  //   name: "Avatar 7",
  //   position: [0, -120, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-tee-shirt-and-pants.glb",
  //   price: 250,
  // },
  // {
  //   id: 15,
  //   name: "Avatar 1",
  //   position: [0, -120, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-under.glb",
  //   price: 250,
  // },
  // {
  //   id: 16,
  //   name: "Avatar 1",
  //   position: [0, -120, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/avatar-under-pants.glb",
  //   price: 250,
  // },
  // {
  //   id: 8,
  //   name: "Tech vest",
  //   position: [0, -120, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/Look2.glb",
  //   price: 250,
  // },
];

export default SHOP_DATA;
