const SHOP_DATA = [
  {
    id: 1,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    url: "/models/Coelte.glb",
    price: 250,
  },
  {
    id: 2,
    name: "Wiz Carmagnole Jacket",
    position: [0, -110, -25],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    url: "/models/Casaco.glb",
    price: 670,
  },
  {
    id: 3,
    name: "Wiz Mint Jacket",
    position: [0, -110, -20],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    url: "/models/Colt.glb",
    price: 650,
  },
  {
    id: 4,
    name: "TechBrief Cargo Blue",
    position: [0, -70, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    url: "/models/Pants.glb",
    price: 250,
  },
  {
    id: 5,
    name: "Future cape goth",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    url: "/models/T-shirt black.glb",
    price: 250,
  },
  {
    id: 6,
    name: "Cargo shirt green",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    url: "/models/T-shirt green.glb",
    price: 250,
  },
  {
    id: 7,
    name: "Skin-tight Tee",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    url: "/models/Underwear.glb",
    price: 250,
  },
  // {
  //   id: 8,
  //   name: "Tech vest",
  //   position: [0, -120, 0],
  //   stock: 12,
  //   qrCode: "https://go.echo3d.co/84Vx",
  //   url: "/models/Look2.glb",
  //   price: 250,
  // },
];

export default SHOP_DATA;
