const SHOP_DATA = [
  {
    id: 1,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    imageUrl: "/models/Coelte.glb",
    price: 250,
  },
  {
    id: 2,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    imageUrl: "/models/Casaco.glb",
    price: 250,
  },
  {
    id: 3,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    imageUrl: "/models/Colt.glb",
    price: 250,
  },
  {
    id: 4,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    imageUrl: "/models/Pants.glb",
    price: 250,
  },
  {
    id: 5,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    imageUrl: "/models/T-shirt black.glb",
    price: 250,
  },
  {
    id: 6,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    imageUrl: "/models/T-shirt green.glb",
    price: 250,
  },
  {
    id: 7,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    imageUrl: "/models/Underwear.glb",
    price: 250,
  },
  {
    id: 8,
    name: "Tech vest",
    position: [0, -120, 0],
    stock: 12,
    qrCode: "https://go.echo3d.co/84Vx",
    imageUrl: "/models/Look2.glb",
    price: 250,
  },
];

export default SHOP_DATA;
